# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81d1276d70031ee1d86c6fa0ecbf9d893e495b303b531ef149063d0f2b5212379447e6a54e51664f512c0de658c89f1cd66ae8b2c9c5788a72901d631615a801

test:
  secret_key_base: 888b970b4280c55c881023f097e9b6fad1e4f187ac33cbdcf53907a75374ed6217fd937cfc0d471bdb00506efa8877bc4d12f40210a85685c848ac8e0cc9e300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
